// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIwS8p5cQ7mr85slENpI20xITQdnQuwpQ',
    appId: '1:509571345126:web:56592f73d2f2e428646927',
    messagingSenderId: '509571345126',
    projectId: 'mobile3-5a523',
    authDomain: 'mobile3-5a523.firebaseapp.com',
    databaseURL: 'https://mobile3-5a523-default-rtdb.firebaseio.com',
    storageBucket: 'mobile3-5a523.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgcV3IO2dN7r7N29gP5wQdv0ctzhzqyCE',
    appId: '1:509571345126:android:053f8cdf7d4d9e3a646927',
    messagingSenderId: '509571345126',
    projectId: 'mobile3-5a523',
    databaseURL: 'https://mobile3-5a523-default-rtdb.firebaseio.com',
    storageBucket: 'mobile3-5a523.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIcaDh4NZUnVDP5yOUyuAD-Z74ZKIX-P8',
    appId: '1:509571345126:ios:e28f1fa349b490e1646927',
    messagingSenderId: '509571345126',
    projectId: 'mobile3-5a523',
    databaseURL: 'https://mobile3-5a523-default-rtdb.firebaseio.com',
    storageBucket: 'mobile3-5a523.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIcaDh4NZUnVDP5yOUyuAD-Z74ZKIX-P8',
    appId: '1:509571345126:ios:e28f1fa349b490e1646927',
    messagingSenderId: '509571345126',
    projectId: 'mobile3-5a523',
    databaseURL: 'https://mobile3-5a523-default-rtdb.firebaseio.com',
    storageBucket: 'mobile3-5a523.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIwS8p5cQ7mr85slENpI20xITQdnQuwpQ',
    appId: '1:509571345126:web:81abcdfebde5d5ae646927',
    messagingSenderId: '509571345126',
    projectId: 'mobile3-5a523',
    authDomain: 'mobile3-5a523.firebaseapp.com',
    databaseURL: 'https://mobile3-5a523-default-rtdb.firebaseio.com',
    storageBucket: 'mobile3-5a523.firebasestorage.app',
  );
}
